#include "global.h"
#include "spares.h"

void spares_init(void)
{
  cbi(SPARE1_DDR , SPARE1_BIT);
  sbi(SPARE1_PORT, SPARE1_BIT);

  cbi(SPARE2_DDR , SPARE2_BIT);
  sbi(SPARE2_PORT, SPARE2_BIT);

  cbi(SPARE3_DDR , SPARE3_BIT);
  sbi(SPARE3_PORT, SPARE3_BIT);

  cbi(SPARE4_DDR , SPARE4_BIT);
  sbi(SPARE4_PORT, SPARE4_BIT);

  cbi(SPARE5_DDR , SPARE5_BIT);
  sbi(SPARE5_PORT, SPARE5_BIT);

  cbi(SPARE6_DDR , SPARE6_BIT);
  sbi(SPARE6_PORT, SPARE6_BIT);

  cbi(SPARE7_DDR , SPARE7_BIT);
  sbi(SPARE7_PORT, SPARE7_BIT);

/*  cbi(SPARE8_DDR , SPARE8_BIT); */
/*  sbi(SPARE8_PORT, SPARE8_BIT); */

  cbi(SPARE9_DDR , SPARE9_BIT);
  sbi(SPARE9_PORT, SPARE9_BIT);

  cbi(SPARE10_DDR , SPARE10_BIT);
  sbi(SPARE10_PORT, SPARE10_BIT);

  cbi(SPARE11_DDR , SPARE11_BIT);
  sbi(SPARE11_PORT, SPARE11_BIT);

  cbi(SPARE12_DDR , SPARE12_BIT);
  sbi(SPARE12_PORT, SPARE12_BIT);

  cbi(SPARE13_DDR , SPARE13_BIT);
  sbi(SPARE13_PORT, SPARE13_BIT);

  cbi(SPARE14_DDR , SPARE14_BIT);
  sbi(SPARE14_PORT, SPARE14_BIT);

  cbi(SPARE15_DDR , SPARE15_BIT);
  sbi(SPARE15_PORT, SPARE15_BIT);

  cbi(SPARE16_DDR , SPARE16_BIT);
  sbi(SPARE16_PORT, SPARE16_BIT);

  cbi(SPARE17_DDR , SPARE17_BIT);
  sbi(SPARE17_PORT, SPARE17_BIT);

  cbi(SPARE18_DDR , SPARE18_BIT);
  sbi(SPARE18_PORT, SPARE18_BIT);

  cbi(SPARE19_DDR , SPARE19_BIT);
  sbi(SPARE19_PORT, SPARE19_BIT);

  cbi(SPARE20_DDR , SPARE20_BIT);
  sbi(SPARE20_PORT, SPARE20_BIT);

  cbi(SPARE21_DDR , SPARE21_BIT);
  sbi(SPARE21_PORT, SPARE21_BIT);
}
